// expo-sqlite's web backend (wa-sqlite) ships a .wasm binary
// (node_modules/expo-sqlite/web/wa-sqlite/wa-sqlite.wasm) that it imports
// directly. Metro's default asset extension list (expo/metro-config)
// doesn't include "wasm", so it tries to resolve/parse the file as a JS
// module instead of bundling it as a static asset — this is what produces
// "Unable to resolve './wa-sqlite/wa-sqlite.wasm'" on `expo start --web`.
// Registering it as an asset extension is the documented fix.
const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

config.resolver.assetExts.push("wasm");

// expo-sqlite's web backend also needs the tab to be cross-origin isolated
// (window.crossOriginIsolated === true) — its Worker uses a SharedArrayBuffer
// to talk back to the main thread synchronously (WorkerChannel.ts's
// `syncTrait`), and SharedArrayBuffer is only exposed in an isolated
// context. `expo start --web`'s dev server doesn't send the required
// Cross-Origin-Opener-Policy/Cross-Origin-Embedder-Policy headers by
// default, so in a browser that doesn't already happen to be isolated,
// SharedArrayBuffer is undefined, the worker's sync-response path fails
// silently inside the Worker (no message ever reaches the main thread),
// and getDb()'s promise (src/db/index.ts) hangs forever instead of
// resolving or rejecting — which then blocks every other DB read in the
// app, since that promise is memoized. A prior pass (see DECISIONS.md,
// 2026-07-21) checked this once and concluded headers weren't needed —
// true in whatever browser that was tested in, not universally.
//
// COEP: "credentialless" (not "require-corp") is deliberate — it still
// makes the tab cross-origin isolated, but doesn't require every
// cross-origin resource this app loads (CARTO map tiles, Google Places/
// Routes responses) to opt in with their own Cross-Origin-Resource-Policy
// header; it just strips credentials from those requests instead of
// blocking them outright. "require-corp" would need each third party's
// cooperation and risks silently breaking the map tiles this same session
// was already investigating.
//
// Metro's own `server.enhanceMiddleware` hook (tried first) only wraps
// Metro's *bundle-serving* connect middleware — confirmed by inspecting
// @expo/cli's instantiateMetro.js: the actual "/" document response is
// generated by a separate ManifestMiddleware registered later on the same
// connect app, which never passes through `enhanceMiddleware`'s result.
// That's a real, verified gap, not a guess: the JS bundle response carried
// these headers, the HTML document didn't. A global `http.ServerResponse`
// patch is the only hook that reliably covers every route (document,
// bundle, assets, manifest) regardless of which internal middleware ends
// up writing the response — non-destructive (only sets a header if the
// response doesn't already have one), and scoped to this dev-time Node
// process only; it has no effect on production builds or EAS, since
// metro.config.js only runs inside the local Metro/Expo CLI process.
const http = require("http");
const originalWriteHead = http.ServerResponse.prototype.writeHead;
http.ServerResponse.prototype.writeHead = function patchedWriteHead(...args) {
  if (!this.getHeader("Cross-Origin-Opener-Policy")) {
    this.setHeader("Cross-Origin-Opener-Policy", "same-origin");
  }
  if (!this.getHeader("Cross-Origin-Embedder-Policy")) {
    this.setHeader("Cross-Origin-Embedder-Policy", "credentialless");
  }
  return originalWriteHead.apply(this, args);
};

module.exports = config;
